name: build

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        make install
    - name: Run Tests
      run: |
        make test
      env:
        PUBLISH_TOKEN: none
        SECRET_KEY: none
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        name: codecov-mymusichere
        
  deploy:
    
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    
    runs-on: ubuntu-latest
  
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Deploy
      run: |
        ssh ${{ secrets.USER }}@${{ secrets.HOST }} 'cd ~/mymusichere.me && git stash && git pull && git stash pop'
        ssh ${{ secrets.USER }}@${{ secrets.HOST }} 'cd ~/mymusichere.me && workon mymusichere && python manage.py migrate'
        ssh ${{ secrets.USER }}@${{ secrets.HOST }} 'cd ~/mymusichere.me && workon mymusichere && make install && make css && make static'
        curl -H 'Authorization: Token ${{ secrets.TOKEN }}' -X POST https://www.pythonanywhere.com/api/v0/user/${{ secrets.USER }}/webapps/www.mymusichere.me/reload
